allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@rolldown/binding-win32-x64-msvc@1.2.12'
  - '@vitest/coverage-istanbul@5.0.3'
  - '@vitest/mocker@5.0.3'
  - '@vitest/spy@5.0.3'
  - vitest@5.0.3
